spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;MODE=MySQL       # 使用内存数据库（应用重启后数据丢失）
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true                  # 打印SQL语句（调试用）
    properties:
      hibernate:
        format_sql: true            # 格式化SQL输出
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true                 # 启用H2控制台
      path: /h2-console             # H2控制台访问路径\
      settings:
        web-allow-others: true
