server:
  servlet:
    context-path: /homework  # 业务域/服务  即ddd的 业务域/子域

spring:
  application:
    name: homework

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "Asia/Shanghai"
    parser:
      allow-comments: true



  profiles:
    # 环境配置
    active: @profiles.active@

  main:
    allow-circular-references: true